bug: missing server.imas_remote_host
simdb.cli.remote_api.RemoteError: Cannot process IMAS data as server.imas_remote_host configuration option not set